version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/var/www/html/uploads
    depends_on:
      - php-fpm

  php-fpm:
    build: ./php
    volumes:
      - ./php:/var/www/html
      - ./uploads:/var/www/html/uploads
