version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - uploads:/var/www/html/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_CLIENT_MAX_BODY_SIZE=10M
  
  php:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./src/uploads:/var/www/html/uploads
    environment:
      - UPLOAD_MAX_FILESIZE=10M
      - POST_MAX_SIZE=10M

volumes:
  uploads:
