#version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "6969:80"
    volumes:
      - ./src:/var/www/html/src
      - /home/snowfall/Server:/var/www/html/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_CLIENT_MAX_BODY_SIZE=10M
  
  php:
    build: .
    volumes:
      - ./:/var/www/html
      - /home/snowfall/Server:/var/www/html/src/uploads
      - ./composer.json:/var/www/html/composer.json
    environment:
      - UPLOAD_MAX_FILESIZE=1024M
      - POST_MAX_SIZE=1024M

volumes:
  uploads:
